#!/usr/bin/python
#  GENIVI Connection Manager
#
#  Copyright (C) 2010  BMW Car IT GmbH. All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


import sys
import dbus

bus = dbus.SystemBus()

id = "0"
if len(sys.argv) > 1:
    id = sys.argv[1]

path = "/service/%s" % (id)

try:
    gcm_service = bus.get_object('org.genivi.gcm', path)
    gcm_service.ConnectionRelease(dbus_interface = 'org.genivi.gcm.GcmService')
except:
    print "connection release call failed"

try:
    gcm = bus.get_object('org.genivi.gcm', '/')
    gcm.DestroyGcmService(path, dbus_interface = 'org.genivi.gcm.Manager')
except:
    print "destruction of gcm service failed"
